

spring:
  datasource:
    dbcp2:
      url: jdbc:mysql://192.168.0.48:3306/CWKIM_DB?useSSL=false
      username: cwkim
      password: cwkim1234
      driver-class-name: com.mysql.jdbc.Driver
      
      
  jpa:
     hibernate:
       ddl-auto: create
       naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     generate-ddl: true
     show-sql: true
     database: mysql
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     properties:
       hibernate:
         format_sql: true
         
         
#password 암호화 사용유     
msp:
  security:
    password:
      encoding: false
      
  upload:                     ## 첨부파일 관련 설정
    enable: true
    path: /svc/dev/data/upload
    maxSize: 1
    maxCount: 1    