
spring:
  datasource:
    dbcp2:
      url: jdbc:mysql://localhost:3306/TESTDB?allowPublicKeyRetrieval=true&useSSL=false
      username: cwkim
      password: 1111
      driver-class-name: com.mysql.jdbc.Driver
      
      
  jpa:
     hibernate:
       ddl-auto: create
       naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     generate-ddl: false
     show-sql: true
     database: mysql
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     properties:
       hibernate:
         format_sql: true


   
  
debug: true

#password 암호화 사용유     
msp:
  security:
    password:
      encoding: false

  upload:                 ## 첨부파일 관련 설정
    enable: true
    path: /svc/dev/data/upload
    maxSize: 1
    maxCount: 1 